# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-12 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_orientation_required'),
        ('store', '0002_coursecheckout_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecheckout',
            name='event',
        ),
        migrations.AddField(
            model_name='coursecheckout',
            name='events',
            field=models.ManyToManyField(help_text=b'Select the studio hours that can be picked for this checkout.', to='event.Event'),
        ),
    ]
