# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0008_auto_20161111_2219'),
        ('course', '0008_auto_20161129_1748'),
        ('store', '0002_auto_20161108_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drop.Product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Session')),
            ],
            options={
                'abstract': False,
            },
            bases=(media.models.PhotosMixin, 'drop.product'),
        ),
    ]
