# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-14 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20170419_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('order',)},
        ),
    ]
