# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-09 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20161122_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='user',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
