# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-03 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_auto_20170109_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unsubscribelink',
            name='user',
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='notify_global',
            field=models.BooleanField(default=True, help_text=b'Uncheck this to stop all correspondance from this website (same as setting all of the following to "Do not notify me about this")', verbose_name=b'Global Email Preference'),
        ),
        migrations.DeleteModel(
            name='UnsubscribeLink',
        ),
    ]
