# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-24 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_auto_20170109_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='my_classes',
            field=models.CharField(blank=True, choices=[(b'', b'Do not notify me about this'), (b'email', b'Email'), (b'sms', b'Text Message (SMS, standard rates apply)')], default=b'', help_text=b"An email or text reminder 24 hours before a class (that you've signed up for or are teaching).", max_length=8, verbose_name=b'Class Reminder'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='new_comments',
            field=models.CharField(blank=True, choices=[(b'', b'Do not notify me about this'), (b'email', b'Email'), (b'sms', b'Text Message (SMS, standard rates apply)')], default=b'', help_text=b'An email or text whenever someone replies to a comment you make on this site.', max_length=8, verbose_name=b'Comment responses'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='new_sessions',
            field=models.CharField(blank=True, choices=[(b'', b'Do not notify me about this'), (b'email', b'Email'), (b'sms', b'Text Message (SMS, standard rates apply)')], default=b'', help_text=b"An email or text when a class you're following for has been added (only during business hours).", max_length=8, verbose_name=b'New Classes'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='notify_global',
            field=models.BooleanField(default=True, help_text=b'Uncheck this to stop all correspondance from this website (same as setting all of the following to "Do not notify me about this")', verbose_name=b'Global Email Preference'),
        ),
    ]
