# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-03 11:03
from __future__ import unicode_literals

from django.db import migrations

def transfer_notify(apps,schema_editor):
    for user in apps.get_model("user.user").objects.all():
        membership = apps.get_model("membership.usermembership").objects.get_or_create(user=user)[0]
        settings = apps.get_model("notify.notifysettings").objects.get_or_create(user=user)[0]
        settings.new_comments = "email" if membership.notify_comments else ""
        settings.my_classes = "email" if membership.notify_classes else ""
        settings.new_sessions = "email"
        settings.save()

class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_auto_20170303_1055'),
        ('notify','0004_auto_20170303_1100'),
    ]

    operations = [
        migrations.RunPython(transfer_notify,lambda *args:None)
    ]
