# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-24 12:05
from __future__ import unicode_literals

from django.db import migrations

def transfer_notify(apps,schema_editor):
    UserMembership = apps.get_model("membership.usermembership")
    UserMembership.objects.filter(notify_comments=True).update(new_comments="email")
    UserMembership.objects.filter(notify_comments=False).update(new_comments="")

    UserMembership.objects.filter(notify_classes=True).update(my_classes="email")
    UserMembership.objects.filter(notify_classes=False).update(my_classes="")

    UserMembership.objects.all().update(new_sessions="email")

class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_auto_20170224_1122'),
    ]

    operations = [
        migrations.RunPython(transfer_notify,lambda *args:None)
    ]
