# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-09 22:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_auto_20170303_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitedaccesskey',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 38, 11, 728783)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 38, 15, 737247)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officer',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 38, 20, 811815)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 38, 26, 785126)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 38, 31, 568020)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='limitedaccesskey',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
