# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-13 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20170913_1554'),
        ('course', '0002_auto_20170419_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='eventoccurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.EventOccurrence'),
        ),
    ]
