# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_session_overbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
