# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0001_initial'),
        ('course', '0008_auto_20161129_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drop.Product')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.Session')),
            ],
            bases=('drop.product',),
        ),
    ]
