# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-23 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_sessionproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='failed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
