# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-09 22:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20170331_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubscription',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 37, 32, 376095)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 37, 35, 904218)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 37, 39, 872505)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 37, 44, 492674)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 37, 49, 384116)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[(b'new', b'New'), (b'failed', b'Failed'), (b'completed', b'Completed'), (b'incomplete', b'Incomplete')], default=b'new', max_length=16),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[(b'new', b'New'), (b'failed', b'Failed'), (b'completed', b'Completed'), (b'incomplete', b'Incomplete')], default=b'new', max_length=16),
        ),
    ]
