# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-16 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20170409_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
