# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-12 17:45
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0004_rfidlog_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidlog',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
