# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-19 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import lablackey.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('content', models.TextField(blank=True, null=True)),
                ('login_required', models.BooleanField(default=False, help_text=b'If checked, user must log into site before viewing/signing document')),
                ('editable', models.BooleanField(default=True, help_text=b'After submitting the document can the creator edit it?If false a new document will be created everytime they submit the document.')),
            ],
            bases=(models.Model, lablackey.db.models.JsonMixin),
        ),
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, help_text=b'For fields with the same label', max_length=64, null=True)),
                ('order', models.IntegerField(default=999)),
                ('input_type', models.CharField(choices=[(b'text', b'Text'), (b'textarea', b'Textarea (multi-line)'), (b'number', b'Number'), (b'phone', b'Phone'), (b'email', b'Email'), (b'header', b'Design Element (non-input)'), (b'checkbox', b'Checkbox'), (b'select', b'Select'), (b'checkbox-input', b'Select Multiple'), (b'signature', b'Sign Your Name'), (b'multi-file', b'Multiple File'), (b'services', b'"Services"')], max_length=64)),
                ('data', jsonfield.fields.JSONField(blank=True, default=dict, help_text=b'Json object for field generation. Will overwrite any other database entry (name, label, etc.)')),
                ('required', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.IntegerField(default=0)),
                ('member_price', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'new', b'New'), (b'failed', b'Failed'), (b'completed', b'Completed'), (b'incomplete', b'Incomplete')], default=b'new', max_length=16)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_changed', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redtape.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
