# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-02 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redtape', '0019_auto_20161228_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
