# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-07 19:09
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('redtape', '0020_delete_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfield',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
