# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-07 19:15
from __future__ import unicode_literals

from django.db import migrations
import json

def move_choices(apps,schema_editor):
    documentfields = apps.get_model('redtape.documentfield').objects.filter(choices__isnull=False)
    for documentfield in documentfields:
        documentfield.data['choices'] = json.loads(documentfield.choices)
        print len(documentfield.data['choices']),documentfield
        documentfield.save()

class Migration(migrations.Migration):

    dependencies = [
        ('redtape', '0021_documentfield_data'),
    ]

    operations = [
        migrations.RunPython(move_choices,lambda a,b:None)
    ]
