# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-08 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('redtape', '0021_documentfield_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.IntegerField(default=0)),
                ('member_price', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.RemoveField(
            model_name='documentfield',
            name='choices',
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, default=dict, help_text=b'Json object for field generation. Will overwrite any other database entry (name, label, etc.)'),
        ),
        migrations.AlterField(
            model_name='documentfield',
            name='input_type',
            field=models.CharField(choices=[(b'text', b'Text'), (b'textarea', b'Textarea (multi-line)'), (b'number', b'Number'), (b'phone', b'Phone'), (b'email', b'Email'), (b'header', b'Design Element (non-input)'), (b'checkbox', b'Checkbox'), (b'select', b'Select'), (b'checkbox-input', b'Select Multiple'), (b'signature', b'Sign Your Name'), (b'multi-file', b'Multiple File'), (b'services', b'"Services"')], max_length=64),
        ),
    ]
