# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-09 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redtape', '0026_auto_20170331_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='status',
            field=models.CharField(choices=[(b'new', b'New'), (b'failed', b'Failed'), (b'completed', b'Completed'), (b'incomplete', b'Incomplete')], default=b'new', max_length=16),
        ),
    ]
