# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-09 22:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0002_auto_20160927_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 39, 48, 704866)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 39, 51, 940372)),
            preserve_default=False,
        ),
    ]
