# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-09 22:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 37, 19, 809015)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 37, 28, 298213)),
            preserve_default=False,
        ),
    ]
