# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-11 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20160927_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, b'Sunday'), (1, b'Monday'), (2, b'Tuesday'), (3, b'Wednesday'), (4, b'Thursday'), (5, b'Fridayday'), (6, b'Saturday')], null=True)),
                ('week_number', models.IntegerField(choices=[(999, b'Every Week'), (0, b'First week'), (1, b' Second week'), (2, b' Third week'), (3, b' Fourth week'), (-1, b'Last week of month'), (-2, b'Second to last week of month'), (-3, b'Third to last week of month')])),
                ('first_date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
    ]
