# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-13 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20160927_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRepeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat_flavor', models.CharField(choices=[(b'start-month', b'Weekly, from start of month (eg, 1st, 2nd... Friday of month)'), (b'end-month', b'Weekly from end of month (eg, second to last friday of month'), (b'weekly', b'Every Week')], max_length=16)),
                ('first_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
        migrations.AddField(
            model_name='eventoccurrence',
            name='eventrepeat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.EventRepeat'),
        ),
    ]
