# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-13 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170213_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='repeat',
        ),
    ]
