# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-13 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20170213_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='icon',
        ),
    ]
