# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-16 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_event_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventrepeat',
            options={},
        ),
        migrations.AlterField(
            model_name='event',
            name='access',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.Access'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventrepeat',
            name='repeat_flavor',
            field=models.CharField(choices=[(b'start-month', b'Monthly from start of month (eg, 1st, 2nd... Friday of month)'), (b'end-month', b'Monthly from end of month (eg, second to last friday of month'), (b'weekly', b'Every Week'), (b'custom', b'Custom')], max_length=16),
        ),
    ]
