# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-13 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0007_auto_20170216_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='allow_rsvp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='hidden',
            field=models.BooleanField(default=False, help_text=b"Hidden events won't appear on the calendar."),
        ),
        migrations.AddField(
            model_name='eventowner',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
        migrations.AddField(
            model_name='eventowner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
