# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-23 16:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_rsvp_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='failed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
