# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-31 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20170323_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[(b'new', b'New'), (b'failed', b'Failed'), (b'complete', b'Completed'), (b'incomplete', b'Incomplete')], default=b'new', max_length=16),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='status_changed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
