# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-31 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20170331_1831'),
        ('tool', '0009_auto_20170331_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='failed',
        ),
    ]
