# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-09 22:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20170331_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 37, 54, 606149)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkin',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 37, 58, 219330)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventowner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 38, 2, 488217)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventowner',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 38, 6, 475474)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[(b'new', b'New'), (b'failed', b'Failed'), (b'completed', b'Completed'), (b'incomplete', b'Incomplete')], default=b'new', max_length=16),
        ),
    ]
