#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export PROJECT_ROOT=$DIR/../../
MIGRATIONS=`find $PROJECT_ROOT -name 00*.py |wc -l`
GIT_WORK_TREE=../ git checkout -f

cd $PROJECT_ROOT

echo -e "\n---Silently migrating, compressing, collecting static, and restarting---\n"

if [ $MIGRATIONS != `find $PROJECT_ROOT -name 00*.py |wc -l` ];
    then
    python $PROJECT_ROOT/manage.py migrate --noinput>/dev/null
done
cd $PROJECT_ROOT/.dev/unrest/; gulp
cd $PROJECT_ROOT/.dev/drop/; gulp
cd $PROJECT_ROOT; gulp

python $PROJECT_ROOT/manage.py collectstatic --noinput>/dev/null
python $PROJECT_ROOT/manage.py compress>/dev/null

bash $PROJECT_ROOT/server/uwsgi.sh
