#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export PROJECT_ROOT=$DIR/../../

GIT_WORK_TREE=../ git checkout -f

cd $PROJECT_ROOT

echo -e "\n---Silently migrating, compressing, collecting static, and restarting---\n"

python $PROJECT_ROOT/manage.py migrate --noinput>/dev/null
python $PROJECT_ROOT/manage.py collectstatic --noinput>/dev/null
python $PROJECT_ROOT/manage.py compress>/dev/null

bash $PROJECT_ROOT/server/uwsgi.sh
