SEARCH_STRINGS = (
  'sony',
  'symbian',
  'nokia',
  'samsung',
  'mobile',
  'windows ce',
  'epoc',
  'opera mini',
  'nitro',
  'j2me',
  'midp-',
  'cldc-',
  'netfront',
  'mot',
  'up.browser',
  'up.link',
  'audiovox',
  'blackberry',
  'ericsson,',
  'panasonic',
  'philips',
  'sanyo',
  'sharp',
  'sie-',
  'portalmmm',
  'blazer',
  'avantgo',
  'danger',
  'palm',
  'series60',
  'palmsource',
  'pocketpc',
  'smartphone',
  'rover',
  'ipaq',
  'au-mic,',
  'alcatel',
  'ericy',
  'up.link',
  'docomo',
  'vodafone/',
  'wap1.',
  'wap2.',
  'plucker',
  '480x640',
  'sec',
  # The Google transcoder
  'google wireless transcoder',
  # These are games consoles that either have a small screen or display on a
  # TV. Best to treat them as mobiles for web display
  'nintendo',
  'webtv',
  'playstation',
  'webos',
  'opera mobi',
  'fennec'
)
