# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-19 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20170419_1352'),
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionschedule',
            name='levels',
            field=models.ManyToManyField(to='membership.Level'),
        ),
    ]
