# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-26 00:46
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_toolcheckoutitemgroup'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usercriterion',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
