# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-23 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20170313_1117'),
        ('tool', '0006_auto_20161126_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='events',
            field=models.ManyToManyField(blank=True, to='event.Event'),
        ),
    ]
