# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-31 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_criterion_events'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usercriterion',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='criterion',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text=b'If a user enrolls in any of these classes and then is marked "complete", this criteria will be granted to that user.', to='course.Course'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='events',
            field=models.ManyToManyField(blank=True, help_text=b'If a user RSVPs for any of these events and then is marked "complete", this criteria will be granted to that user.', to='event.Event'),
        ),
    ]
