# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-24 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='orientation_status',
        ),
    ]
