# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-05 18:15
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_orientation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
