# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-08 11:06
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='src',
            field=models.FileField(blank=True, max_length=200, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=b'/media_files/private/', location=b'/home/chriscauley/txrx.org/.private'), upload_to=b'%Y%m'),
        ),
    ]
