# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-16 17:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0004_auto_20170108_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 16, 17, 7, 20, 134199)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 4, 16, 17, 7, 26, 357559)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_mediauploadedfiles', to='sessions.Session'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_mediauploadedfiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
