# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-19 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import lablackey.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_id', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-datetime',),
            },
            bases=(models.Model, lablackey.db.models.JsonMixin),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('emailed', models.DateTimeField(blank=True, null=True)),
                ('read', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(max_length=512)),
                ('data', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('relationship', models.CharField(blank=True, max_length=32, null=True)),
                ('target_type', models.CharField(blank=True, max_length=201, null=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-datetime',),
            },
            bases=(models.Model, lablackey.db.models.JsonMixin),
        ),
        migrations.CreateModel(
            name='NotifySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_global', models.BooleanField(default=True, help_text=b'If false this wil disable all notificaitons from the site.', verbose_name=b'Global Preference')),
                ('new_comments', models.CharField(choices=[(b'email', b'Email'), (b'sms', b'Text Message*'), (b'none', b'Do not notify')], default=b'email', help_text=b'An email or text whenever someone replies to a comment you make on this site.', max_length=8, verbose_name=b'Comment responses')),
                ('my_classes', models.CharField(choices=[(b'email', b'Email'), (b'sms', b'Text Message*'), (b'none', b'Do not notify')], default=b'email', help_text=b"An email or text reminder 24 hours before a class (that you've signed up for or are teaching).", max_length=8, verbose_name=b'Class Reminders')),
                ('new_sessions', models.CharField(choices=[(b'email', b'Email'), (b'sms', b'Text Message*'), (b'none', b'Do not notify')], default=b'email', help_text=b"An email or text when a class you're following for has been added (only during business hours).", max_length=8, verbose_name=b'New Classes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
