# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-24 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import notify.models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20170419_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expires',
            field=models.DateTimeField(default=notify.models.default_expires),
        ),
    ]
