# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-16 06:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_notification_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifysettings',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 16, 6, 35, 4, 779129)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifysettings',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 8, 16, 6, 35, 7, 860229)),
            preserve_default=False,
        ),
    ]
