# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-20 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_auto_20170303_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifysettings',
            name='my_classes',
            field=models.CharField(choices=[(b'email', b'Email'), (b'sms', b'Text Message*'), (b'none', b'Do not notify')], default=b'email', help_text=b"An email or text reminder 24 hours before a class (that you've signed up for or are teaching).", max_length=8, verbose_name=b'Class Reminders'),
        ),
        migrations.AlterField(
            model_name='notifysettings',
            name='new_comments',
            field=models.CharField(choices=[(b'email', b'Email'), (b'sms', b'Text Message*'), (b'none', b'Do not notify')], default=b'email', help_text=b'An email or text whenever someone replies to a comment you make on this site.', max_length=8, verbose_name=b'Comment responses'),
        ),
        migrations.AlterField(
            model_name='notifysettings',
            name='new_sessions',
            field=models.CharField(choices=[(b'email', b'Email'), (b'sms', b'Text Message*'), (b'none', b'Do not notify')], default=b'email', help_text=b"An email or text when a class you're following for has been added (only during business hours).", max_length=8, verbose_name=b'New Classes'),
        ),
    ]
