# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-22 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_auto_20170221_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='emailed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
