# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-09 22:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_auto_20170320_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 38, 35, 790741)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follow',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 39, 23, 291153)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 39, 31, 749964)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 39, 35, 338794)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifycourse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 39, 38, 961611)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifycourse',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 9, 22, 39, 44, 699243)),
            preserve_default=False,
        ),
    ]
