# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-27 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0006_notification_emailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='follow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notify.Follow'),
        ),
    ]
