# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-28 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0007_auto_20170227_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='relationship',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
