# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-19 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0007_auto_20170416_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifycourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='notifycourse',
            name='user',
        ),
        migrations.DeleteModel(
            name='NotifyCourse',
        ),
    ]
